version: '3'
services:
  app:
    build:
      context: .
      args:
        - source=${SOURCE_DIR}
    volumes:
      - src:/var/code
      - db:/var/mysql
    networks:
      - default
    tty: true
    restart: always
  mysql:
#    image: mysql:${MYSQL_VERSION}
    build: ./Docker/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      default:
        aliases:
          - ${MYSQL_HOST_NAME}
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  phpfpm:
    build:
      context: ./Docker/php-fpm
    volumes:
      - src:/var/www/html
      - socket:/var/run
    networks:
      - default
    restart: always
  nginx:
    build:
      context: ./Docker/nginx
    volumes:
      - src:/usr/share/nginx/html
      - socket:/var/run
    ports:
      - ${WEB_PORT}:80
    networks:
      - default
    healthcheck:
      test: ["CMD", "echo", "healthcheck……"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      - phpfpm
    restart: always

networks:
  default:

volumes:
  src:
  db:
  socket:
