version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      args:
        - phpfpm_host=phpfpm
    volumes:
      - src:/usr/share/nginx/html
      - socket:/var/run
    ports:
      - 1308:80
    networks:
      - default
    depends_on:
      - phpfpm
    restart: always
  phpfpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - src:/var/www/html
      - socket:/var/run
    networks:
      - default
    restart: always
networks:
  default:

volumes:
  src:
  socket:
